export const OBJECT_PLATE_FILES = [
  "object-noticeboard",
  "object-courtyard-well",
  "object-school-banners",
  "object-borrowing-register",
  "object-breathing-wheel",
  "object-slate-labels",
  "object-practice-rules",
  "object-key-board",
  "object-ink-blotter",
  "object-flood-marker",
  "object-place-card",
  "object-listening-stone",
  "object-watering-jug",
  "object-star-wheel",
  "object-snail-sundial",
  "object-folded-page",
  "object-blackboard",
  "object-recipe-slate",
  "object-seedling-tray",
  "object-bee-skep",
  "object-dream-mobile",
  "object-sock-puppet",
  "object-empty-bell-frame",
  "object-bell-ledger",
  "object-promise-mosaic",
  "object-wayboard",
  "small-copper-key",
  "practice-sword",
  "practice-staff",
  "practice-sling",
  "moss-bound-primer",
  "object-silk-thread",
  "object-stair-rope",
  "object-caught-lantern",
  "object-waking-husk",
  "object-still-score",
  "straw-practice-scrap",
  "torn-silk-strand",
  "queen-silk-cord",
  "object-holm-wrapping",
  "object-colm-aftermath",
  "object-wool-wrap",
  "object-colms-crook",
  "object-empty-peg",
  "object-empty-fold",
  "object-waystone",
  "object-abbey-mark",
  "object-new-stone",
  "object-abbey-bronze",
  "object-shed-skin",
  "object-no-footprints",
  "object-peat-water",
  "wren-wool-charm",
  "wren-hearth-charm",
  "abbey-mark-rubbing",
  "object-kitchen-initials",
  "patched-hood",
  "fog-glass-bead",
  "peat-lantern",
  "abbey-mark-ring",
  "moor-boots",
  "linen-wrap",
  "path-boots",
  "wooden-guard",
  "slate-cap",
  "glass-ring",
  "quiet-cloak",
  "thorn-ring",
  "hearth-mitts",
  "object-wool-pegs",
  "object-empty-stall",
  "object-lane-mist",
  "object-still-water",
  "object-scratch-stone",
  "object-pale-grass",
  "object-black-water",
  "object-stile-stone",
  "object-cut-painter",
  "object-withy-bundles",
  "object-reed-bundles",
  "object-empty-ring",
  "object-biscuit-shelf",
  "object-thief-knot",
  "object-still-wheel",
  "object-rope-coil",
  "object-whistle-post",
  "object-turnip-tins",
  "object-biscuit-crate",
  "object-tarred-post",
  "porters-cord",
  "hearth-biscuit",
  "ink-rag",
  "fold-mitts",
  "reed-cloak",
  "lintel-band",
  "river-boots",
  "biscuit-tin",
  "skipper-whistle",
  "boarding-oar",
  "fold-bell",
  "wisp-glass",
  "ditch-nail",
  "deck-token",
  "cut-rope",
  "captain-coat",
  "river-stone",
  "crow-pin",
  "peat-nail",
  "cut-iron",
  "pressed-mask",
  "object-tally-slate",
  "object-drying-frames",
  "borrowed-ink",
  "quires-focus-ring",
  "vanes-wick-tin",
  "shellington-diary",
  "cellar-lavender",
  "oak-and-bronze-book",
  "withy-ring",
  "terns-copied-column",
  "fold-tally-page",
  "raiders-token",
] as const;

const OBJECT_PLATE_ALIASES: Record<string, string> = Object.fromEntries(
  OBJECT_PLATE_FILES.map((id) => [id, id]),
);

const PLACEMENT_ALIASES: Record<string, string> = {
  "object-school-chart": "object-school-banners",
  "object-hall-banners": "object-school-banners",
  "object-ember-grate": "object-practice-rules",
  "object-thorn-trellis": "object-seedling-tray",
  "object-veil-mirror": "object-listening-stone",
  "object-stars-wheel": "object-star-wheel",
  "object-stone-keystone": "object-promise-mosaic",
  "object-steel-anvil": "object-practice-rules",
  "object-orchard-apples": "object-seedling-tray",
  "item-straw-practice-scrap": "straw-practice-scrap",
  "item-torn-silk-strand": "torn-silk-strand",
  "item-queen-silk-cord": "queen-silk-cord",
  "item-enemy-practice-dummy-south-orchard-loot-straw-practice-scrap": "straw-practice-scrap",
  "item-enemy-silk-hatchling-cocoon-nave-loot-torn-silk-strand": "torn-silk-strand",
  "item-enemy-silk-queen-deep-cradle-loot-queen-silk-cord": "queen-silk-cord",
  "librarians-ribbon": "object-folded-page",
  "tansy-seed-pouch": "object-seedling-tray",
  "listening-charm": "object-listening-stone",
  "piper-stair-charm": "object-stair-rope",
  "copied-still-score": "object-still-score",
  "item-quest-the-missing-pages-loot-librarians-ribbon": "object-folded-page",
  "item-quest-a-little-room-to-grow-loot-tansy-seed-pouch": "object-seedling-tray",
  "item-quest-the-bell-below-loot-listening-charm": "object-listening-stone",
  "item-quest-the-bell-wakes-loot-piper-stair-charm": "object-stair-rope",
  "item-quest-what-still-sleeps-loot-copied-still-score": "object-still-score",
  "item-quest-the-uncounted-flock-loot-wren-wool-charm": "wren-wool-charm",
  "item-quest-the-thing-that-walks-loot-wren-hearth-charm": "wren-hearth-charm",
  "item-enemy-fog-walker-fog-hollow-loot-wren-hearth-charm": "wren-hearth-charm",
  "item-copper-key-lantern-court": "small-copper-key",
  "item-practice-sword-south-orchard": "practice-sword",
  "item-practice-staff-south-orchard": "practice-staff",
  "item-practice-sling-south-orchard": "practice-sling",
  "item-primer-library-stacks": "moss-bound-primer",
  "item-field-primer-lantern-court": "moss-bound-primer",
  "field-primer": "moss-bound-primer",
  "item-abbey-mark-rubbing-standing-stones": "abbey-mark-rubbing",
};

function slug(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export function objectArtSrc(id: string, name?: string): string | undefined {
  const exact = OBJECT_PLATE_ALIASES[id] ?? PLACEMENT_ALIASES[id];
  if (exact) return `/art/objects/${exact}.png`;
  const named = name ? slug(name) : "";
  for (const plate of OBJECT_PLATE_FILES) {
    if (id.includes(plate) || (named && (plate === named || plate === `object-${named}`))) {
      return `/art/objects/${plate}.png`;
    }
  }
  return undefined;
}
